package com.Chapter_14_ERRORS_AND_EXCEPTION;

/*  1.
    try {
    ...
    } catch() {
    ...
    }


    2.
    try {
    ...
    } catch() {
    ...
    } catch() {
    ...
    }


    3.
    try {
        try {
        ...
        } catch() {
        ...
        }
    } catch() {
    ...
    }


    4.
    try {
    ...
    } catch() {
        try {
        ...
        } catch() {
        ...
        }
    }


    5.
    try {
    ...
    } catch() {
    ...
    } finally {
    ...
    }


    6.
    try {
    ...
    } finally {
    ...
    }


    7.
    try {
    ...
    } finally {
        try {
        ...
        } catch() {
        ...
    }
 */
public class Ch_14_6_Try_Catch_Finally_Combinations {
}
